let progress = loadProgress(), selectedLetters = [], builderCompleted = false, lessonCompleted = false, reviewMode = false, speakKeyDetailsOpen = false, speakAssemblyOpen = false, speakAssemblyCompleted = false, selectedSpeakChunks = [], availableSpeakChunks = [], speakAssemblyItemId = null, speakAssemblyFeedback = "";
setLocale(progress.locale);
const $ = (id) => document.getElementById(id);
const homeScreen=$("home-screen"), lessonScreen=$("lesson-screen"), wordCard=$("word-card"), builderCard=$("builder-card"), lessonList=$("lesson-list"), arabicWord=$("arabic-word"), meaning=$("translation"), progressCount=$("lesson-progress-count"), progressFill=$("lesson-progress-fill"), streakCount=$("streak-count"), xpCount=$("xp-count"), lettersContainer=$("letters"), answerSlots=$("answer-slots"), feedback=$("builder-feedback"), checkButton=$("check-answer"), audioButton=$("play-audio"), audioLabel=$("audio-button-label"), audioStatus=$("audio-status"), greetingName=$("greeting-name"), audioController=new AudioPlaybackController(setAudioState);
const wordIllustration=$("word-illustration"), wordImage=$("word-image"), speakStageShell=$("speak-stage-shell"), speakPosition=$("speak-stage-position"), speakPhrase=$("speak-stage-phrase"), speakMeaning=$("speak-stage-meaning"), speakKeyTrigger=$("speak-key-trigger"), speakKeyLabel=$("speak-key-label"), speakKeyArabic=$("speak-key-arabic"), speakKeyMeaning=$("speak-key-meaning"), speakKeyDetails=$("speak-key-details"), speakKeyDetailsTitle=$("speak-key-details-title"), speakKeyDetailsArabic=$("speak-key-details-arabic"), speakKeyDetailsMeaning=$("speak-key-details-meaning"), speakKeyClose=$("speak-key-close"), speakPracticeTrigger=$("speak-practice-trigger"), speakAssembly=$("speak-assembly"), speakAssemblyInstruction=$("speak-assembly-instruction"), speakAssemblyAnswer=$("speak-assembly-answer"), speakAssemblyOptions=$("speak-assembly-options"), speakAssemblyFeedbackElement=$("speak-assembly-feedback"), speakAssemblyReset=$("speak-assembly-reset"), speakAssemblyCheck=$("speak-assembly-check"), speakPrevious=$("speak-previous"), speakNext=$("speak-next");
const expandStageShell=$("expand-stage-shell"), expandPosition=$("expand-stage-position"), expandBaseArabic=$("expand-base-arabic"), expandBaseMeaning=$("expand-base-meaning"), expandAddedArabic=$("expand-added-arabic"), expandPhrase=$("expand-stage-phrase"), expandMeaning=$("expand-stage-meaning"), expandPrevious=$("expand-previous"), expandNext=$("expand-next");
const topicStageNav=$("topic-stage-nav");
const lessonTitle=(lesson)=>lesson.titles[activeLocale]||lesson.titles.ru, lessonDescription=(lesson)=>lesson.descriptions[activeLocale]||lesson.descriptions.ru;
function getCurrentLesson(){return lessons.find((lesson)=>lesson.id===progress.currentLessonId)||lessons[0];}
function getCurrentWord(){const lesson=getCurrentLesson();if(progress.currentWord>=lesson.words.length)setWordsPosition(lesson,0);return lesson.words[progress.currentWord];}
function setWordsPosition(lesson,position){const max=Math.max(lesson.words.length-1,0),next=Number.isInteger(position)&&position>=0?Math.min(position,max):0;progress.currentWord=next;setCurrentTopicStage(progress,lesson.id,"words");updateTopicStageProgress(progress,lesson.id,"words",{position:next});return next;}
function restoreWordsPosition(lesson,allowLegacy=false){const hasTopic=Object.prototype.hasOwnProperty.call(progress.topicProgress||{},lesson.id),saved=hasTopic?getTopicStageProgress(progress,lesson.id,"words"):null;return setWordsPosition(lesson,saved?saved.position:(allowLegacy?progress.currentWord:0));}
function getSpeakPosition(lesson){const items=Array.isArray(lesson.speak)?lesson.speak:[],max=Math.max(items.length-1,0),stage=getTopicStageProgress(progress,lesson.id,"speak"),saved=stage&&stage.position,next=Number.isInteger(saved)&&saved>=0?Math.min(saved,max):0;if(stage&&stage.position!==next){updateTopicStageProgress(progress,lesson.id,"speak",{position:next});saveProgress(progress);}return next;}
function setSpeakPosition(lesson,position){const max=Math.max((lesson.speak||[]).length-1,0),next=Number.isInteger(position)&&position>=0?Math.min(position,max):0;setCurrentTopicStage(progress,lesson.id,"speak");updateTopicStageProgress(progress,lesson.id,"speak",{position:next});saveProgress(progress);return next;}
function getExpandPosition(lesson){const items=Array.isArray(lesson.expand)?lesson.expand:[],max=Math.max(items.length-1,0),stage=getTopicStageProgress(progress,lesson.id,"expand"),saved=stage&&stage.position,next=Number.isInteger(saved)&&saved>=0?Math.min(saved,max):0;if(stage&&stage.position!==next){updateTopicStageProgress(progress,lesson.id,"expand",{position:next});saveProgress(progress);}return next;}
function setExpandPosition(lesson,position){const max=Math.max((lesson.expand||[]).length-1,0),next=Number.isInteger(position)&&position>=0?Math.min(position,max):0;setCurrentTopicStage(progress,lesson.id,"expand");updateTopicStageProgress(progress,lesson.id,"expand",{position:next});saveProgress(progress);return next;}
function mastered(words){return words.filter((word)=>progress.learnedWordIds.includes(word.id)).length;}
function isLessonComplete(lesson){return mastered(lesson.words)===lesson.words.length;}
function getNextIncompleteLesson(){return lessons.find((lesson)=>!isLessonComplete(lesson))||null;}function getResumeLesson(){const current=lessons.find((lesson)=>lesson.id===progress.currentLessonId);return current&&!isLessonComplete(current)?current:getNextIncompleteLesson();}
function showScreen(screen){homeScreen.hidden=screen!=="home";lessonScreen.hidden=screen!=="lesson";}
function setSpeakKeyDetails(open,{focusClose=false,restoreFocus=false}={}){speakKeyDetailsOpen=Boolean(open);speakKeyTrigger.setAttribute("aria-expanded",String(speakKeyDetailsOpen));speakKeyDetails.hidden=!speakKeyDetailsOpen;if(speakKeyDetailsOpen&&focusClose)speakKeyClose.focus();if(!speakKeyDetailsOpen&&restoreFocus)speakKeyTrigger.focus();}
function shuffleSpeakChunks(chunks){const shuffled=chunks.map((text,index)=>({id:index,text}));for(let index=shuffled.length-1;index>0;index-=1){const swapIndex=Math.floor(Math.random()*(index+1));[shuffled[index],shuffled[swapIndex]]=[shuffled[swapIndex],shuffled[index]];}return shuffled;}
function resetSpeakAssembly(){speakAssemblyOpen=false;speakAssemblyCompleted=false;selectedSpeakChunks=[];availableSpeakChunks=[];speakAssemblyItemId=null;speakAssemblyFeedback="";}
function startSpeakAssembly(){const lesson=getCurrentLesson(),item=lesson.speak[getSpeakPosition(lesson)];if(!item||!Array.isArray(item.chunks)||!item.chunks.length)return;setSpeakKeyDetails(false);speakAssemblyOpen=true;speakAssemblyCompleted=false;selectedSpeakChunks=[];availableSpeakChunks=shuffleSpeakChunks(item.chunks);speakAssemblyItemId=item.id;speakAssemblyFeedback="";renderLesson();}
function getSpeakAssemblyItem(lesson){const item=lesson.speak[getSpeakPosition(lesson)];return speakAssemblyOpen&&item&&item.id===speakAssemblyItemId?item:null;}
function renderSpeakChunk(container,chunk,selected){const button=document.createElement("button");button.type="button";button.className="speak-chunk";button.textContent=chunk.text;button.disabled=speakAssemblyCompleted;button.addEventListener("click",()=>{if(speakAssemblyCompleted)return;if(selected){selectedSpeakChunks=selectedSpeakChunks.filter((item)=>item.id!==chunk.id);availableSpeakChunks.push(chunk);}else{availableSpeakChunks=availableSpeakChunks.filter((item)=>item.id!==chunk.id);selectedSpeakChunks.push(chunk);}speakAssemblyFeedback="";renderLesson();});container.appendChild(button);}
function renderSpeakAssembly(lesson){const item=getSpeakAssemblyItem(lesson);speakAssembly.hidden=!item;speakPracticeTrigger.hidden=Boolean(item);speakPhrase.hidden=Boolean(item&&!speakAssemblyCompleted);if(!item)return;speakAssemblyInstruction.textContent=t("speakAssemblyInstruction");speakAssemblyAnswer.setAttribute("aria-label",t("speakAssemblyAnswer"));speakAssemblyOptions.setAttribute("aria-label",t("speakAssemblyOptions"));speakAssemblyAnswer.innerHTML="";speakAssemblyOptions.innerHTML="";selectedSpeakChunks.forEach((chunk)=>renderSpeakChunk(speakAssemblyAnswer,chunk,true));availableSpeakChunks.forEach((chunk)=>renderSpeakChunk(speakAssemblyOptions,chunk,false));speakAssemblyFeedbackElement.className=`speak-assembly-feedback${speakAssemblyFeedback?` is-${speakAssemblyFeedback}`:""}`;speakAssemblyFeedbackElement.textContent=speakAssemblyFeedback?t(`speakAssembly${speakAssemblyFeedback==="success"?"Correct":"Wrong"}`):"";speakAssemblyReset.textContent=t("speakAssemblyReset");speakAssemblyCheck.textContent=t("speakAssemblyCheck");speakAssemblyCheck.disabled=speakAssemblyCompleted||selectedSpeakChunks.length!==item.chunks.length;}
function checkSpeakAssembly(){const lesson=getCurrentLesson(),item=getSpeakAssemblyItem(lesson);if(!item||speakAssemblyCompleted||selectedSpeakChunks.length!==item.chunks.length)return;if(selectedSpeakChunks.map((chunk)=>chunk.text).join(" ")===item.chunks.join(" ")){speakAssemblyCompleted=true;speakAssemblyFeedback="success";}else speakAssemblyFeedback="error";renderLesson();}
function isStageAvailable(lesson,stageId){return stageId==="words"||(stageId==="speak"&&Array.isArray(lesson.speak)&&lesson.speak.length>0)||(stageId==="expand"&&Array.isArray(lesson.expand)&&lesson.expand.length>0);}
function getCurrentStage(lesson){const topic=getOrCreateTopicProgress(progress,lesson.id),stageId=topic.currentStageId;return isStageAvailable(lesson,stageId)?stageId:"words";}
function selectTopicStage(stageId){const lesson=getCurrentLesson();if(!isStageAvailable(lesson,stageId))return;setSpeakKeyDetails(false);resetSpeakAssembly();if(stageId==="words")restoreWordsPosition(lesson);else if(stageId==="speak")getSpeakPosition(lesson);else if(stageId==="expand")getExpandPosition(lesson);setCurrentTopicStage(progress,lesson.id,stageId);reviewMode=false;saveProgress(progress);renderLesson();}
function renderTopicStages(lesson,activeStage){const keys={words:"stageWords",speak:"stageSpeak",expand:"stageExpand",understand:"stageUnderstand",dialogue:"stageDialogue",practice:"stagePractice"};topicStageNav.setAttribute("aria-label",t("topicStages"));topicStageNav.innerHTML="";LEARNING_STAGES.forEach((stage)=>{const available=isStageAvailable(lesson,stage.id),button=document.createElement("button"),status=available?"":`<span class="topic-stage-status">${t("stageComingSoon")}</span>`;button.type="button";button.className="topic-stage";button.disabled=!available;button.setAttribute("aria-current",stage.id===activeStage?"step":"false");button.innerHTML=`<span class="topic-stage-number">${stage.number}</span><span class="topic-stage-label">${t(keys[stage.id])}</span>${status}`;if(available)button.addEventListener("click",()=>selectTopicStage(stage.id));topicStageNav.appendChild(button);});}
function renderHeader(){streakCount.textContent=progress.streak;xpCount.textContent=progress.xp;}
function staticText(){ $("home-eyebrow").textContent=t("homeEyebrow");$("greeting-prefix").textContent=t("greeting");$("home-intro").textContent=t("intro");$("overall-label").textContent=t("overall");$("lessons-title").textContent=t("lessons");$("back-to-home").textContent=t("back");$("lesson-progress-label").textContent=t("lessonProgress");$("start-builder").textContent=t("build");$("repeat-word").textContent=t("repeat");$("next-word").textContent=t("known");$("builder-eyebrow").textContent=t("builderEyebrow");$("builder-title").textContent=t("builderTitle");$("reset-answer").textContent=t("reset");if(!builderCompleted)checkButton.textContent=t("check");$("language-label").textContent=t("language");$("locale-ru").textContent=t("russian");$("locale-uz").textContent=t("uzbek");document.querySelector(".header-stats").setAttribute("aria-label",t("progressSummary"));document.querySelector(".summary-card").setAttribute("aria-label",t("overall"));document.querySelector(".lesson-progress").setAttribute("aria-label",t("lessonProgress"));answerSlots.setAttribute("aria-label",t("answer"));lettersContainer.setAttribute("aria-label",t("letters")); }
function setAudioState(state){const word=getCurrentWord(),hasAudio=Boolean(word.audio&&word.audio.src);audioStatus.className="audio-status";if(!hasAudio||state==="missing"){audioButton.disabled=true;audioLabel.textContent=t("audioMissing");audioStatus.textContent=t("audioMissingStatus");return;}audioButton.disabled=state==="loading";if(state==="loading"){audioLabel.textContent=t("audioLoading");audioStatus.textContent="";}else if(state==="playing"){audioLabel.textContent=t("audioReplay");audioStatus.textContent=t("audioPlaying");}else if(state==="error"){audioLabel.textContent=t("audioRetry");audioStatus.textContent=t("audioError");audioStatus.classList.add("is-error");}else{audioLabel.textContent=t("audioPlay");audioStatus.textContent="";}}
function renderImage(word){
  const src=word.image&&word.image.src;

  if(!src){
    wordIllustration.hidden=true;
    wordImage.removeAttribute("src");
    wordImage.alt="";
    return;
  }

  wordIllustration.hidden=false;
  wordImage.alt=word.translations[activeLocale]||word.translations.ru||"";
  wordImage.onerror=()=>{
    wordIllustration.hidden=true;
    wordImage.removeAttribute("src");
  };
  wordImage.src=src;
}
function renderAudio(word){audioController.stop();setAudioState(word.audio&&word.audio.src?"idle":"missing");}
function renderHome(){audioController.stop();staticText();greetingName.hidden=true;greetingName.textContent="";const count=mastered(allWords),resumeLesson=getResumeLesson();$("overall-progress").textContent=t("words",{current:count,total:allWords.length});$("overall-progress-fill").style.width=`${count/allWords.length*100}%`;$("streak-description").textContent=t("streak",{count:progress.streak,unit:progress.streak===1?t("day"):t("days")});$("lesson-count").textContent=t("lessonCount",{count:lessons.length});$("continue-lesson").textContent=resumeLesson?t("continue",{lesson:lessonTitle(resumeLesson)}):t("allLessonsComplete");$("continue-lesson").disabled=!resumeLesson;lessonList.innerHTML="";lessons.forEach((lesson,index)=>{const button=document.createElement("button"),count=mastered(lesson.words);button.className="lesson-card";button.type="button";button.innerHTML=`<span class="lesson-number">${t("lesson",{count:index+1})}</span><strong>${lessonTitle(lesson)}</strong><span>${lessonDescription(lesson)}</span><span class="lesson-card-progress">${t("words",{current:count,total:lesson.words.length})}</span>`;button.addEventListener("click",()=>openLesson(lesson.id));lessonList.appendChild(button);});renderHeader();}
function openLesson(id){const lesson=lessons.find((item)=>item.id===id)||lessons[0],changed=progress.currentLessonId!==lesson.id;setSpeakKeyDetails(false);resetSpeakAssembly();progress.currentLessonId=lesson.id;if(getCurrentStage(lesson)==="words")restoreWordsPosition(lesson,!changed);reviewMode=false;saveProgress(progress);showScreen("lesson");renderLesson();}
function renderWordsStage(lesson){const word=getCurrentWord();$("word-position").textContent=t("wordPosition",{current:progress.currentWord+1,total:lesson.words.length});arabicWord.textContent=word.arabic;meaning.textContent=word.translations[activeLocale]||word.translations.ru;renderImage(word);renderAudio(word);speakStageShell.hidden=true;expandStageShell.hidden=true;builderCard.hidden=true;wordCard.hidden=false;$("learning-actions").hidden=false;}
function renderSpeakStage(lesson,position){const speakItems=lesson.speak||[],item=speakItems[position],key=lesson.speechKeys.find((speechKey)=>speechKey.id===item.speechKeyId);$("speak-stage-kicker").textContent=t("speakStageKicker");speakPosition.textContent=t("speakPosition",{current:position+1,total:speakItems.length});speakPhrase.textContent=item.arabic;speakMeaning.textContent=item.translations[activeLocale]||item.translations.ru;speakKeyLabel.textContent=t("speakKeyLabel");speakKeyArabic.textContent=key.arabic;speakKeyMeaning.textContent=key.translations[activeLocale]||key.translations.ru;speakKeyDetailsTitle.textContent=t("speakKeyDetailsTitle");speakKeyDetailsArabic.textContent=key.arabic;speakKeyDetailsMeaning.textContent=key.translations[activeLocale]||key.translations.ru;speakKeyClose.textContent=t("speakKeyClose");setSpeakKeyDetails(speakKeyDetailsOpen);speakPracticeTrigger.textContent=t("speakPractice");renderSpeakAssembly(lesson);speakPrevious.textContent=t("speakPrevious");speakNext.textContent=t("speakNext");speakPrevious.disabled=position===0;speakNext.disabled=position===speakItems.length-1;audioController.stop();wordCard.hidden=true;expandStageShell.hidden=true;builderCard.hidden=true;$("learning-actions").hidden=true;speakStageShell.hidden=false;}
function renderExpandStage(lesson,position){const expandItems=lesson.expand||[],item=expandItems[position],baseSpeak=(lesson.speak||[]).find((speak)=>speak.id===item.baseSpeakId);$("expand-stage-kicker").textContent=t("expandStageKicker");expandPosition.textContent=t("expandPosition",{current:position+1,total:expandItems.length});$("expand-base-label").textContent=t("expandBaseLabel");expandBaseArabic.textContent=baseSpeak?baseSpeak.arabic:"";expandBaseMeaning.textContent=baseSpeak?(baseSpeak.translations[activeLocale]||baseSpeak.translations.ru):"";$("expand-added-label").textContent=t("expandAddedLabel");expandAddedArabic.textContent=item.addedArabic;$("expand-phrase-label").textContent=t("expandPhraseLabel");expandPhrase.textContent=item.arabic;expandMeaning.textContent=item.translations[activeLocale]||item.translations.ru;expandPrevious.textContent=t("expandPrevious");expandNext.textContent=t("expandNext");expandPrevious.disabled=position===0;expandNext.disabled=position===expandItems.length-1;audioController.stop();wordCard.hidden=true;speakStageShell.hidden=true;builderCard.hidden=true;$("learning-actions").hidden=true;expandStageShell.hidden=false;}
function renderLesson(){lessonCompleted=false;builderCard.classList.remove("lesson-complete-card");staticText();const lesson=getCurrentLesson(),activeStage=getCurrentStage(lesson),count=mastered(lesson.words);if(activeStage!==getOrCreateTopicProgress(progress,lesson.id).currentStageId){setCurrentTopicStage(progress,lesson.id,activeStage);saveProgress(progress);}renderTopicStages(lesson,activeStage);$("lesson-kicker").textContent=t("lesson",{count:lessons.indexOf(lesson)+1});$("lesson-title").textContent=lessonTitle(lesson);$("lesson-description").textContent=lessonDescription(lesson);if(activeStage==="speak"){const position=getSpeakPosition(lesson),total=lesson.speak.length;progressCount.textContent=t("speakPosition",{current:position+1,total});progressFill.style.width=`${(position+1)/total*100}%`;renderSpeakStage(lesson,position);}else if(activeStage==="expand"){const position=getExpandPosition(lesson),total=lesson.expand.length;progressCount.textContent=t("expandPosition",{current:position+1,total});progressFill.style.width=`${(position+1)/total*100}%`;renderExpandStage(lesson,position);}else{progressCount.textContent=t("words",{current:count,total:lesson.words.length});progressFill.style.width=`${count/lesson.words.length*100}%`;renderWordsStage(lesson);}renderHeader();}
function openBuilder(){wordCard.hidden=true;builderCard.hidden=false;$("learning-actions").hidden=true;renderBuilder();}
function renderBuilder(){const word=getCurrentWord();selectedLetters=[];builderCompleted=false;lettersContainer.innerHTML="";answerSlots.innerHTML="";feedback.textContent=t("builderInstruction");feedback.className="builder-feedback";checkButton.disabled=true;checkButton.textContent=t("check");[...word.letters].sort(()=>Math.random()-.5).forEach((letter)=>{const button=document.createElement("button");button.className="letter-button";button.type="button";button.textContent=letter;button.addEventListener("click",()=>{selectedLetters.push(letter);const slot=document.createElement("span");slot.className="slot";slot.textContent=letter;answerSlots.appendChild(slot);button.remove();checkButton.disabled=selectedLetters.length!==word.letters.length;});lettersContainer.appendChild(button);});}
function award(word){recordLearningActivity(progress);if(!progress.learnedWordIds.includes(word.id))progress.learnedWordIds.push(word.id);if(!progress.xpAwardedWordIds.includes(word.id)){progress.xpAwardedWordIds.push(word.id);progress.xp+=10;}saveProgress(progress);}
function checkAnswer(){if(builderCompleted){next();return;}const word=getCurrentWord();progress.attempts+=1;if(selectedLetters.join("")===word.letters.join("")){progress.correctAnswers+=1;award(word);feedback.textContent=t("correct");feedback.className="builder-feedback is-success";checkButton.textContent=t("next");builderCompleted=true;}else{saveProgress(progress);feedback.textContent=t("wrong",{word:word.arabic});feedback.className="builder-feedback is-error";}renderHeader();}
function renderLessonComplete(){const lesson=getCurrentLesson(),count=mastered(lesson.words),nextLesson=getNextIncompleteLesson();$("lesson-title").textContent=lessonTitle(lesson);$("lesson-description").textContent=lessonDescription(lesson);progressCount.textContent=t("words",{current:count,total:lesson.words.length});progressFill.style.width=`${count/lesson.words.length*100}%`;lessonCompleted=true;wordCard.hidden=true;builderCard.hidden=false;builderCard.classList.add("lesson-complete-card");$("learning-actions").hidden=true;$("builder-eyebrow").textContent=t("lessonCompleteEyebrow");$("builder-title").textContent=nextLesson?t("lessonCompleteTitle"):t("allLessonsComplete");answerSlots.innerHTML="";lettersContainer.innerHTML="";feedback.textContent=nextLesson?t("lessonCompleteDescription"):t("allLessonsCompleteDescription");feedback.className="builder-feedback";$("reset-answer").textContent=t("reviewLesson");checkButton.textContent=nextLesson?t("nextLesson"):t("backToLessons");checkButton.disabled=false;}
function next(){const lesson=getCurrentLesson();if(reviewMode){if(progress.currentWord>=lesson.words.length-1){reviewMode=false;saveProgress(progress);renderLessonComplete();return;}setWordsPosition(lesson,progress.currentWord+1);saveProgress(progress);renderLesson();return;}if(isLessonComplete(lesson)){saveProgress(progress);renderLessonComplete();return;}setWordsPosition(lesson,(progress.currentWord+1)%lesson.words.length);saveProgress(progress);renderLesson();}
function changeLocale(locale){progress.locale=translations[locale]?locale:"ru";setLocale(progress.locale);saveProgress(progress);if(!lessonScreen.hidden){if(lessonCompleted)renderLessonComplete();else renderLesson();}else renderHome();}
$("home-button").addEventListener("click",()=>{setSpeakKeyDetails(false);resetSpeakAssembly();showScreen("home");renderHome();});$("back-to-home").addEventListener("click",()=>{setSpeakKeyDetails(false);resetSpeakAssembly();showScreen("home");renderHome();});$("continue-lesson").addEventListener("click",()=>{const resumeLesson=getResumeLesson();if(resumeLesson)openLesson(resumeLesson.id);});$("next-word").addEventListener("click",()=>{if(!reviewMode)award(getCurrentWord());next();});$("repeat-word").addEventListener("click",openBuilder);$("start-builder").addEventListener("click",openBuilder);$("reset-answer").addEventListener("click",()=>{if(lessonCompleted){reviewMode=true;lessonCompleted=false;setWordsPosition(getCurrentLesson(),0);saveProgress(progress);renderLesson();}else renderBuilder();});audioButton.addEventListener("click",()=>audioController.play(getCurrentWord().audio&&getCurrentWord().audio.src));checkButton.addEventListener("click",()=>{if(!lessonCompleted){checkAnswer();return;}const nextLesson=getNextIncompleteLesson();if(nextLesson)openLesson(nextLesson.id);else{setSpeakKeyDetails(false);resetSpeakAssembly();showScreen("home");renderHome();}});speakKeyTrigger.addEventListener("click",()=>setSpeakKeyDetails(true,{focusClose:true}));speakKeyClose.addEventListener("click",()=>setSpeakKeyDetails(false,{restoreFocus:true}));speakPracticeTrigger.addEventListener("click",startSpeakAssembly);speakAssemblyReset.addEventListener("click",startSpeakAssembly);speakAssemblyCheck.addEventListener("click",checkSpeakAssembly);document.addEventListener("keydown",(event)=>{if(event.key==="Escape"&&speakKeyDetailsOpen)setSpeakKeyDetails(false,{restoreFocus:true});});speakPrevious.addEventListener("click",()=>{const lesson=getCurrentLesson();setSpeakKeyDetails(false);resetSpeakAssembly();setSpeakPosition(lesson,getSpeakPosition(lesson)-1);renderLesson();});speakNext.addEventListener("click",()=>{const lesson=getCurrentLesson();setSpeakKeyDetails(false);resetSpeakAssembly();setSpeakPosition(lesson,getSpeakPosition(lesson)+1);renderLesson();});$("locale-ru").addEventListener("click",()=>changeLocale("ru"));$("locale-uz").addEventListener("click",()=>changeLocale("uz"));renderHome();
expandPrevious.addEventListener("click",()=>{const lesson=getCurrentLesson();setExpandPosition(lesson,getExpandPosition(lesson)-1);renderLesson();});expandNext.addEventListener("click",()=>{const lesson=getCurrentLesson();setExpandPosition(lesson,getExpandPosition(lesson)+1);renderLesson();});
