let progress = loadProgress(), selectedLetters = [], builderCompleted = false;
setLocale(progress.locale);
const $ = (id) => document.getElementById(id);
const homeScreen=$("home-screen"), lessonScreen=$("lesson-screen"), wordCard=$("word-card"), builderCard=$("builder-card"), lessonList=$("lesson-list"), arabicWord=$("arabic-word"), meaning=$("translation"), progressCount=$("lesson-progress-count"), progressFill=$("lesson-progress-fill"), streakCount=$("streak-count"), xpCount=$("xp-count"), lettersContainer=$("letters"), answerSlots=$("answer-slots"), feedback=$("builder-feedback"), checkButton=$("check-answer"), audioButton=$("play-audio"), audioLabel=$("audio-button-label"), audioStatus=$("audio-status"), greetingName=$("greeting-name"), audioController=new AudioPlaybackController(setAudioState);
const lessonTitle=(lesson)=>lesson.titles[activeLocale]||lesson.titles.ru, lessonDescription=(lesson)=>lesson.descriptions[activeLocale]||lesson.descriptions.ru;
function getCurrentLesson(){return lessons.find((lesson)=>lesson.id===progress.currentLessonId)||lessons[0];}
function getCurrentWord(){const lesson=getCurrentLesson();if(progress.currentWord>=lesson.words.length)progress.currentWord=0;return lesson.words[progress.currentWord];}
function mastered(words){return words.filter((word)=>progress.learnedWordIds.includes(word.id)).length;}
function showScreen(screen){homeScreen.hidden=screen!=="home";lessonScreen.hidden=screen!=="lesson";}
function renderHeader(){streakCount.textContent=progress.streak;xpCount.textContent=progress.xp;}
function staticText(){ $("home-eyebrow").textContent=t("homeEyebrow");$("greeting-prefix").textContent=t("greeting");$("home-intro").textContent=t("intro");$("overall-label").textContent=t("overall");$("lessons-title").textContent=t("lessons");$("back-to-home").textContent=t("back");$("lesson-progress-label").textContent=t("lessonProgress");$("start-builder").textContent=t("build");$("repeat-word").textContent=t("repeat");$("next-word").textContent=t("known");$("builder-eyebrow").textContent=t("builderEyebrow");$("builder-title").textContent=t("builderTitle");$("reset-answer").textContent=t("reset");if(!builderCompleted)checkButton.textContent=t("check");$("language-label").textContent=t("language");$("locale-ru").textContent=t("russian");$("locale-uz").textContent=t("uzbek"); }
function setAudioState(state){const word=getCurrentWord(),hasAudio=Boolean(word.audio&&word.audio.src);audioStatus.className="audio-status";if(!hasAudio||state==="missing"){audioButton.disabled=true;audioLabel.textContent=t("audioMissing");audioStatus.textContent=t("audioMissingStatus");return;}audioButton.disabled=state==="loading";if(state==="loading"){audioLabel.textContent=t("audioLoading");audioStatus.textContent="";}else if(state==="playing"){audioLabel.textContent=t("audioReplay");audioStatus.textContent=t("audioPlaying");}else if(state==="error"){audioLabel.textContent=t("audioRetry");audioStatus.textContent=t("audioError");audioStatus.classList.add("is-error");}else{audioLabel.textContent=t("audioPlay");audioStatus.textContent="";}}
function renderAudio(word){audioController.stop();setAudioState(word.audio&&word.audio.src?"idle":"missing");}
function renderHome(){audioController.stop();staticText();const user=getTelegramUser();greetingName.hidden=!user||!user.first_name;greetingName.textContent=user&&user.first_name?`, ${user.first_name}!`:"";const count=mastered(allWords);$("overall-progress").textContent=t("words",{current:count,total:allWords.length});$("overall-progress-fill").style.width=`${count/allWords.length*100}%`;$("streak-description").textContent=t("streak",{count:progress.streak,unit:progress.streak===1?t("day"):t("days")});$("lesson-count").textContent=t("lessonCount",{count:lessons.length});$("continue-lesson").textContent=t("continue",{lesson:lessonTitle(getCurrentLesson())});lessonList.innerHTML="";lessons.forEach((lesson,index)=>{const button=document.createElement("button"),count=mastered(lesson.words);button.className="lesson-card";button.type="button";button.innerHTML=`<span class="lesson-number">${t("lesson",{count:index+1})}</span><strong>${lessonTitle(lesson)}</strong><span>${lessonDescription(lesson)}</span><span class="lesson-card-progress">${t("words",{current:count,total:lesson.words.length})}</span>`;button.addEventListener("click",()=>openLesson(lesson.id));lessonList.appendChild(button);});renderHeader();}
function openLesson(id){const lesson=lessons.find((item)=>item.id===id)||lessons[0],changed=progress.currentLessonId!==lesson.id;progress.currentLessonId=lesson.id;progress.currentWord=changed?0:Math.min(progress.currentWord,lesson.words.length-1);saveProgress(progress);showScreen("lesson");renderLesson();}
function renderLesson(){staticText();const lesson=getCurrentLesson(),word=getCurrentWord(),count=mastered(lesson.words);$("lesson-kicker").textContent=t("lesson",{count:lessons.indexOf(lesson)+1});$("lesson-title").textContent=lessonTitle(lesson);$("lesson-description").textContent=lessonDescription(lesson);progressCount.textContent=t("words",{current:count,total:lesson.words.length});progressFill.style.width=`${count/lesson.words.length*100}%`;$("word-position").textContent=t("wordPosition",{current:progress.currentWord+1,total:lesson.words.length});arabicWord.textContent=word.arabic;meaning.textContent=word.translations[activeLocale]||word.translations.ru;renderAudio(word);builderCard.hidden=true;wordCard.hidden=false;$("learning-actions").hidden=false;renderHeader();}
function openBuilder(){wordCard.hidden=true;builderCard.hidden=false;$("learning-actions").hidden=true;renderBuilder();}
function renderBuilder(){const word=getCurrentWord();selectedLetters=[];builderCompleted=false;lettersContainer.innerHTML="";answerSlots.innerHTML="";feedback.textContent=t("builderInstruction");feedback.className="builder-feedback";checkButton.disabled=true;checkButton.textContent=t("check");[...word.letters].sort(()=>Math.random()-.5).forEach((letter)=>{const button=document.createElement("button");button.className="letter-button";button.type="button";button.textContent=letter;button.addEventListener("click",()=>{selectedLetters.push(letter);const slot=document.createElement("span");slot.className="slot";slot.textContent=letter;answerSlots.appendChild(slot);button.remove();checkButton.disabled=selectedLetters.length!==word.letters.length;});lettersContainer.appendChild(button);});}
function award(word){recordLearningActivity(progress);if(!progress.learnedWordIds.includes(word.id))progress.learnedWordIds.push(word.id);if(!progress.xpAwardedWordIds.includes(word.id)){progress.xpAwardedWordIds.push(word.id);progress.xp+=10;}saveProgress(progress);}
function checkAnswer(){if(builderCompleted){next();return;}const word=getCurrentWord();progress.attempts+=1;if(selectedLetters.join("")===word.letters.join("")){progress.correctAnswers+=1;award(word);feedback.textContent=t("correct");feedback.className="builder-feedback is-success";checkButton.textContent=t("next");builderCompleted=true;}else{saveProgress(progress);feedback.textContent=t("wrong",{word:word.arabic});feedback.className="builder-feedback is-error";}renderHeader();}
function next(){const lesson=getCurrentLesson();progress.currentWord=(progress.currentWord+1)%lesson.words.length;saveProgress(progress);renderLesson();}
function changeLocale(locale){progress.locale=translations[locale]?locale:"ru";setLocale(progress.locale);saveProgress(progress);if(!lessonScreen.hidden)renderLesson();else renderHome();}
$("home-button").addEventListener("click",()=>{showScreen("home");renderHome();});$("back-to-home").addEventListener("click",()=>{showScreen("home");renderHome();});$("continue-lesson").addEventListener("click",()=>openLesson(progress.currentLessonId));$("next-word").addEventListener("click",()=>{award(getCurrentWord());next();});$("repeat-word").addEventListener("click",openBuilder);$("start-builder").addEventListener("click",openBuilder);$("reset-answer").addEventListener("click",renderBuilder);audioButton.addEventListener("click",()=>audioController.play(getCurrentWord().audio&&getCurrentWord().audio.src));checkButton.addEventListener("click",checkAnswer);$("locale-ru").addEventListener("click",()=>changeLocale("ru"));$("locale-uz").addEventListener("click",()=>changeLocale("uz"));renderHome();
