const understandQuestionAudioPaths = Object.freeze({"03A-U01":"assets/audio/understand/03A/03A-U01-question.mp3","03A-U02":"assets/audio/understand/03A/03A-U02-question.mp3","03A-U03":"assets/audio/understand/03A/03A-U03-question.mp3","03A-U04":"assets/audio/understand/03A/03A-U04-question.mp3","03A-U05":"assets/audio/understand/03A/03A-U05-question.mp3","03A-U06":"assets/audio/understand/03A/03A-U06-question.mp3","03A-U07":"assets/audio/understand/03A/03A-U07-question.mp3","03A-U08":"assets/audio/understand/03A/03A-U08-question.mp3","03A-U09":"assets/audio/understand/03A/03A-U09-question.mp3","03A-U10":"assets/audio/understand/03A/03A-U10-question.mp3"});
const lessons = [
  { id: "first-words", titles: { ru: "Первые слова", uz: "Birinchi so‘zlar" }, descriptions: { ru: "Полезные слова, с которых начинается знакомство с арабским.", uz: "Arab tili bilan tanishishni boshlash uchun foydali so‘zlar." }, words: [
    [1,"كِتَابٌ","Книга","Kitob",["ك","ت","ا","ب"]], [2,"بَيْتٌ","Дом","Uy",["ب","ي","ت"]], [3,"قَلَمٌ","Ручка","Qalam",["ق","ل","م"]], [4,"مَسْجِدٌ","Мечеть","Masjid",["م","س","ج","د"]], [5,"بَابٌ","Дверь","Eshik",["ب","ا","ب"]]
  ] },
  { id: "people-and-family", titles: { ru: "Люди и семья", uz: "Odamlar va oila" }, descriptions: { ru: "Базовые слова о самых близких людях.", uz: "Eng yaqin insonlar haqidagi asosiy so‘zlar." }, words: [
    [6,"أَبٌ","Отец","Ota",["أ","ب"]], [7,"أُمٌّ","Мама","Ona",["أ","م"]], [8,"أَخٌ","Брат","Aka / uka",["أ","خ"]], [9,"أُخْتٌ","Сестра","Opa / singil",["أ","خ","ت"]]
  ] },
  { id: "everyday-things", titles: { ru: "Вокруг нас", uz: "Atrofimizda" }, descriptions: { ru: "Ещё несколько слов для повседневной жизни.", uz: "Kundalik hayot uchun yana bir nechta so‘z." }, words: [
    [10,"مَاءٌ","Вода","Suv",["م","ا","ء"]], [11,"شَمْسٌ","Солнце","Quyosh",["ش","م","س"]], [12,"قَمَرٌ","Луна","Oy",["ق","م","ر"]]
  ] },
  { id: "polite-words", titles: { ru: "Вежливые слова", uz: "Xushmuomala so‘zlar" }, descriptions: { ru: "Короткие слова для приветствия и вежливого общения.", uz: "Salomlashish va xushmuomala suhbat uchun qisqa so‘zlar." }, words: [
    [13,"نَعَمْ","Да","Ha",["ن","ع","م"],true], [14,"لَا","Нет","Yo‘q",["ل","ا"],true], [15,"شُكْرًا","Спасибо","Rahmat",["ش","ك","ر","ا"],true], [16,"مَرْحَبًا","Здравствуйте","Salom",["م","ر","ح","ب","ا"],true]
  ] },
  { id: "introductions", titles: { ru: "Знакомство", uz: "Tanishuv" }, descriptions: { ru: "Слова, чтобы представиться и спросить имя.", uz: "O‘zingizni tanishtirish va ism so‘rash uchun so‘zlar." }, words: [
    [17,"أَنَا","Я","Men",["أ","ن","ا"],true], [18,"أَنْتَ","Ты (м.)","Sen",["أ","ن","ت"],true], [19,"مَنْ","Кто?","Kim?",["م","ن"],true], [20,"اِسْمِي","Моё имя","Mening ismim",["ا","س","م","ي"],true], [21,"اِسْمٌ","Имя","Ism",["ا","س","م"],true], [22,"صَدِيقٌ","Друг","Do‘st",["ص","د","ي","ق"],true]
  ] },
  { id: "numbers-one-to-five", titles: { ru: "Числа 1–5", uz: "1–5 sonlari" }, descriptions: { ru: "Первые числа для счёта в повседневных ситуациях.", uz: "Kundalik holatlarda sanash uchun dastlabki sonlar." }, words: [
    [23,"وَاحِدٌ","Один","Bir",["و","ا","ح","د"],true], [24,"اِثْنَانِ","Два","Ikki",["ا","ث","ن","ا","ن"],true], [25,"ثَلَاثَةٌ","Три","Uch",["ث","ل","ا","ث","ة"],true], [26,"أَرْبَعَةٌ","Четыре","To‘rt",["أ","ر","ب","ع","ة"],true], [27,"خَمْسَةٌ","Пять","Besh",["خ","م","س","ة"],true]
  ] },
  { id: "home-and-rooms", titles: { ru: "Дом и комнаты", uz: "Uy va xonalar" }, descriptions: { ru: "Слова для описания дома и предметов в нём.", uz: "Uy va undagi buyumlarni tasvirlash uchun so‘zlar." }, words: [
    [28,"غُرْفَةٌ","Комната","Xona",["غ","ر","ف","ة"],true], [29,"مَطْبَخٌ","Кухня","Oshxona",["م","ط","ب","خ"],true], [30,"نَافِذَةٌ","Окно","Deraza",["ن","ا","ف","ذ","ة"],true], [31,"كُرْسِيٌّ","Стул","Stul",["ك","ر","س","ي"],true], [32,"سَرِيرٌ","Кровать","Karavot",["س","ر","ي","ر"],true]
  ] },
  { id: "food-and-drinks", titles: { ru: "Еда и напитки", uz: "Ovqat va ichimliklar" }, descriptions: { ru: "Повседневные слова для еды и напитков.", uz: "Ovqat va ichimliklar uchun kundalik so‘zlar." }, words: [
    [33,"مَاءٌ","Вода","Suv",["م","ا","ء"]], [34,"خُبْزٌ","Хлеб","Non",["خ","ب","ز"]], [35,"حَلِيبٌ","Молоко","Sut",["ح","ل","ي","ب"]], [36,"شَايٌ","Чай","Choy",["ش","ا","ي"]], [37,"طَعَامٌ","Еда","Ovqat",["ط","ع","ا","م"]]
  ] },
  { id: "family", titles: { ru: "Семья", uz: "Oila" }, descriptions: { ru: "Слова о семье и близких людях.", uz: "Oila va yaqin insonlar haqidagi so‘zlar." }, words: [
    [38,"أَبٌ","Отец","Ota",["أ","ب"]], [39,"أُمٌّ","Мать","Ona",["أ","م"]], [40,"أَخٌ","Брат","Aka / uka",["أ","خ"]], [41,"أُخْتٌ","Сестра","Opa / singil",["أ","خ","ت"]], [42,"أُسْرَةٌ","Семья","Oila",["أ","س","ر","ة"]]
  ] },
  { id: "clothing", titles: { ru: "Одежда", uz: "Kiyimlar" }, descriptions: { ru: "Слова для одежды и головных уборов.", uz: "Kiyim va bosh kiyimlar uchun so‘zlar." }, words: [
    [43,"ثَوْبٌ","Одежда / тоб","Kiyim / to‘n",["ث","و","ب"]], [44,"قَمِيصٌ","Рубашка","Ko‘ylak",["ق","م","ي","ص"]], [45,"حِذَاءٌ","Обувь","Oyoq kiyim",["ح","ذ","ا","ء"]], [46,"سِرْوَالٌ","Брюки","Shim",["س","ر","و","ا","ل"]], [47,"قُبَّعَةٌ","Головной убор / шапка","Bosh kiyim",["ق","ب","ع","ة"]]
  ] },
  { id: "places-and-city", titles: { ru: "Места и город", uz: "Joylar va shahar" }, descriptions: { ru: "Полезные места в городе.", uz: "Shahardagi foydali joylar." }, words: [
    [48,"مَسْجِدٌ","Мечеть","Masjid",["م","س","ج","د"]], [49,"سُوقٌ","Рынок","Bozor",["س","و","ق"]], [50,"مَطْعَمٌ","Ресторан","Restoran",["م","ط","ع","م"]], [51,"مُسْتَشْفًى","Больница","Kasalxona",["م","س","ت","ش","ف","ى"]], [52,"مَدْرَسَةٌ","Школа","Maktab",["م","د","ر","س","ة"]]
  ] },
{ id: "shop-and-shopping", titles: { ru: "Магазин и покупки", uz: "Do‘kon va xaridlar" }, descriptions: { ru: "Практические слова для магазина, рынка, оплаты и покупок.", uz: "Do‘kon, bozor, to‘lov va xaridlar uchun amaliy so‘zlar." }, words: [
[53,"مَتْجَر","Магазин","Do‘kon",["م","ت","ج","ر"],true,"assets/images/03A/01.jpg"],
[54,"سُوق","Рынок","Bozor",["س","و","ق"],true,"assets/images/03A/02.jpg"],
[55,"مُنْتَج","Товар","Mahsulot",["م","ن","ت","ج"],true,"assets/images/03A/03.jpg"],
[56,"سِعْر","Цена","Narx",["س","ع","ر"],true,"assets/images/03A/04.jpg"],
[57,"خَصْم","Скидка","Chegirma",["خ","ص","م"],true,"assets/images/03A/05.jpg"],
[58,"عَرْض","Акция / предложение","Aksiya / taklif",["ع","ر","ض"],true,"assets/images/03A/06.jpg"],
[59,"فَاتُورَة","Счёт / чек","Hisob / chek",["ف","ا","ت","و","ر","ة"],true,"assets/images/03A/07.jpg"],
[60,"كَاشِير","Кассир","Kassir",["ك","ا","ش","ي","ر"],true,"assets/images/03A/08.jpg"],
[61,"عَرَبَة تَسَوُّق","Тележка","Xarid aravachasi",["ع","ر","ب","ة","ت","س","و","ق"],true,"assets/images/03A/09.jpg"],
[62,"سَلَّة","Корзина","Savat",["س","ل","ة"],true,"assets/images/03A/10.jpg"],
[63,"كِيس","Пакет","Paket",["ك","ي","س"],true,"assets/images/03A/11.jpg"],
[64,"مِيزَان","Весы","Tarozi",["م","ي","ز","ا","ن"],true,"assets/images/03A/12.jpg"],
[65,"كِيلُو","Килограмм","Kilogramm",["ك","ي","ل","و"],true,"assets/images/03A/13.jpg"],
[66,"حَبَّة","Штука","Dona",["ح","ب","ة"],true,"assets/images/03A/14.jpg"],
[67,"مَقَاس","Размер","O‘lcham",["م","ق","ا","س"],true,"assets/images/03A/15.jpg"],
[68,"نَقْد","Наличные","Naqd pul",["ن","ق","د"],true,"assets/images/03A/16.jpg"],
[69,"بِطَاقَة","Карта","Karta",["ب","ط","ا","ق","ة"],true,"assets/images/03A/17.jpg"],
[70,"دَفْع","Оплата","To‘lov",["د","ف","ع"],true,"assets/images/03A/18.jpg"],
[71,"رِيَال","Риял","Riyol",["ر","ي","ا","ل"],true,"assets/images/03A/19.jpg"],
[72,"بَاقِي","Сдача","Qaytim",["ب","ا","ق","ي"],true,"assets/images/03A/20.jpg"]
], speechKeys: [
{ id: "price", arabic: "بِكَم ...؟", translations: { ru: "Сколько стоит ...?", uz: "... qancha turadi?" } },
{ id: "available", arabic: "فِيه ...؟", translations: { ru: "Есть ...?", uz: "... bormi?" } },
{ id: "want", arabic: "أَبْغَى ...", translations: { ru: "Я хочу / мне ...", uz: "Men ... xohlayman / menga ... kerak" } },
{ id: "have", arabic: "عِنْدَك ...؟", translations: { ru: "У тебя / у вас есть ...?", uz: "Sizda ... bormi?" } },
{ id: "pay", arabic: "بَدْفَع ...", translations: { ru: "Я оплачу ...", uz: "Men ... bilan to‘layman" } },
{ id: "where", arabic: "وَيْن ...؟", translations: { ru: "Где ...?", uz: "... qayerda?" } }
], speak: [
{ id: "03A-S01", arabic: "بِكَم هَذَا؟", translations: { ru: "Сколько это стоит?", uz: "Bu qancha turadi?" }, speechKeyId: "price", chunks: ["بِكَم", "هَذَا؟"] },
{ id: "03A-S02", arabic: "فِيه خَصْم؟", translations: { ru: "Есть скидка?", uz: "Chegirma bormi?" }, speechKeyId: "available", chunks: ["فِيه", "خَصْم؟"] },
{ id: "03A-S03", arabic: "أَبْغَى هَذَا", translations: { ru: "Я хочу это", uz: "Men buni xohlayman" }, speechKeyId: "want", chunks: ["أَبْغَى", "هَذَا"] },
{ id: "03A-S04", arabic: "أَبْغَى هَذِي", translations: { ru: "Я хочу это (ж.р.)", uz: "Men buni xohlayman" }, speechKeyId: "want", chunks: ["أَبْغَى", "هَذِي"] },
{ id: "03A-S05", arabic: "عِنْدَك مَقَاس أَكْبَر؟", translations: { ru: "Есть размер побольше?", uz: "Kattaroq o‘lcham bormi?" }, speechKeyId: "have", chunks: ["عِنْدَك", "مَقَاس", "أَكْبَر؟"] },
{ id: "03A-S06", arabic: "عِنْدَك مَقَاس أَصْغَر؟", translations: { ru: "Есть размер поменьше?", uz: "Kichikroq o‘lcham bormi?" }, speechKeyId: "have", chunks: ["عِنْدَك", "مَقَاس", "أَصْغَر؟"] },
{ id: "03A-S07", arabic: "أَبْغَى كِيلُو مِن هَذَا", translations: { ru: "Мне килограмм этого", uz: "Menga bundan bir kilogramm kerak" }, speechKeyId: "want", chunks: ["أَبْغَى", "كِيلُو", "مِن", "هَذَا"] },
{ id: "03A-S08", arabic: "أَبْغَى حَبَّة وَاحْدَة", translations: { ru: "Мне одну штуку", uz: "Menga bittasi kerak" }, speechKeyId: "want", chunks: ["أَبْغَى", "حَبَّة", "وَاحْدَة"] },
{ id: "03A-S09", arabic: "أَبْغَى كِيس", translations: { ru: "Мне пакет", uz: "Menga paket kerak" }, speechKeyId: "want", chunks: ["أَبْغَى", "كِيس"] },
{ id: "03A-S10", arabic: "بَدْفَع بِالْبِطَاقَة", translations: { ru: "Я оплачу картой", uz: "Karta bilan to‘layman" }, speechKeyId: "pay", chunks: ["بَدْفَع", "بِالْبِطَاقَة"] },
{ id: "03A-S11", arabic: "بَدْفَع نَقْد", translations: { ru: "Я оплачу наличными", uz: "Naqd pul bilan to‘layman" }, speechKeyId: "pay", chunks: ["بَدْفَع", "نَقْد"] },
{ id: "03A-S12", arabic: "وَيْن الكَاشِير؟", translations: { ru: "Где касса?", uz: "Kassa qayerda?" }, speechKeyId: "where", chunks: ["وَيْن", "الكَاشِير؟"] }
], expand: [
{ id: "03A-E01", arabic: "بِكَم هَذَا المُنْتَج؟", translations: { ru: "Сколько стоит этот товар?", uz: "Bu mahsulot qancha turadi?" }, baseSpeakId: "03A-S01", addedArabic: "المُنْتَج", chunks: ["بِكَم", "هَذَا", "المُنْتَج؟"] },
{ id: "03A-E02", arabic: "فِيه خَصْم عَلَى هَذَا؟", translations: { ru: "На это есть скидка?", uz: "Bunga chegirma bormi?" }, baseSpeakId: "03A-S02", addedArabic: "عَلَى هَذَا", chunks: ["فِيه", "خَصْم", "عَلَى", "هَذَا؟"] },
{ id: "03A-E03", arabic: "أَبْغَى هَذَا، لَو سَمَحْت", translations: { ru: "Я хочу это, пожалуйста", uz: "Men buni xohlayman, iltimos" }, baseSpeakId: "03A-S03", addedArabic: "لَو سَمَحْت", chunks: ["أَبْغَى", "هَذَا،", "لَو سَمَحْت"] },
{ id: "03A-E04", arabic: "أَبْغَى مَقَاس أَكْبَر مِن هَذَا", translations: { ru: "Мне нужен размер побольше этого", uz: "Menga bundan kattaroq o‘lcham kerak" }, baseSpeakId: "03A-S05", addedArabic: "مِن هَذَا", chunks: ["أَبْغَى", "مَقَاس", "أَكْبَر", "مِن", "هَذَا"] },
{ id: "03A-E05", arabic: "أَبْغَى مَقَاس أَصْغَر مِن هَذَا", translations: { ru: "Мне нужен размер поменьше этого", uz: "Menga bundan kichikroq o‘lcham kerak" }, baseSpeakId: "03A-S06", addedArabic: "مِن هَذَا", chunks: ["أَبْغَى", "مَقَاس", "أَصْغَر", "مِن", "هَذَا"] },
{ id: "03A-E06", arabic: "أَبْغَى كِيلُو مِن هَذَا، لَو سَمَحْت", translations: { ru: "Мне килограмм этого, пожалуйста", uz: "Menga bundan bir kilogramm kerak, iltimos" }, baseSpeakId: "03A-S07", addedArabic: "لَو سَمَحْت", chunks: ["أَبْغَى", "كِيلُو", "مِن", "هَذَا،", "لَو سَمَحْت"] },
{ id: "03A-E07", arabic: "أَبْغَى حَبَّتَيْن مِن هَذَا", translations: { ru: "Мне две штуки этого", uz: "Menga bundan ikkita kerak" }, baseSpeakId: "03A-S08", addedArabic: "حَبَّتَيْن مِن هَذَا", chunks: ["أَبْغَى", "حَبَّتَيْن", "مِن", "هَذَا"] },
{ id: "03A-E08", arabic: "مُمْكِن كِيس، لَو سَمَحْت؟", translations: { ru: "Можно пакет, пожалуйста?", uz: "Paket bersangiz, iltimos?" }, baseSpeakId: "03A-S09", addedArabic: "مُمْكِن ... لَو سَمَحْت؟", chunks: ["مُمْكِن", "كِيس،", "لَو سَمَحْت؟"] },
{ id: "03A-E09", arabic: "مُمْكِن أَدْفَع بِالْبِطَاقَة؟", translations: { ru: "Можно оплатить картой?", uz: "Karta bilan to‘lasam bo‘ladimi?" }, baseSpeakId: "03A-S10", addedArabic: "مُمْكِن أَدْفَع ...؟", chunks: ["مُمْكِن", "أَدْفَع", "بِالْبِطَاقَة؟"] },
{ id: "03A-E10", arabic: "مُمْكِن أَدْفَع نَقْد؟", translations: { ru: "Можно оплатить наличными?", uz: "Naqd pul bilan to‘lasam bo‘ladimi?" }, baseSpeakId: "03A-S11", addedArabic: "مُمْكِن أَدْفَع ...؟", chunks: ["مُمْكِن", "أَدْفَع", "نَقْد؟"] },
{ id: "03A-E11", arabic: "كَم البَاقِي؟", translations: { ru: "Сколько сдачи?", uz: "Qaytim qancha?" }, baseSpeakId: "03A-S01", addedArabic: "البَاقِي", chunks: ["كَم", "البَاقِي؟"] },
{ id: "03A-E12", arabic: "وَيْن أَدْفَع؟", translations: { ru: "Где оплатить?", uz: "Qayerda to‘layman?" }, baseSpeakId: "03A-S12", addedArabic: "أَدْفَع", chunks: ["وَيْن", "أَدْفَع؟"] }
], dialogues: [
{ id: "03A-D01", context: "priceDiscount", translations: { ru: "Цена и скидка", uz: "Narx va chegirma" }, turns: [
{ id: "03A-D01-T01", speaker: "learner", arabic: "بِكَم هَذَا؟", translations: { ru: "Сколько это стоит?", uz: "Bu qancha turadi?" }, audio: { expectedPath: "assets/audio/dialogue/03A/03A-D01-T01.mp3" } },
{ id: "03A-D01-T02", speaker: "interlocutor", arabic: "بِخَمْسِين رِيَال", translations: { ru: "Пятьдесят риялов", uz: "Ellik riyol" }, audio: { expectedPath: "assets/audio/dialogue/03A/03A-D01-T02.mp3" } },
{ id: "03A-D01-T03", speaker: "learner", arabic: "فِيه خَصْم عَلَى هَذَا؟", translations: { ru: "На это есть скидка?", uz: "Bunga chegirma bormi?" }, audio: { expectedPath: "assets/audio/dialogue/03A/03A-D01-T03.mp3" } },
{ id: "03A-D01-T04", speaker: "interlocutor", arabic: "أَيْوَه، فِيه خَصْم عَشَرَة بِالمِيَّة", translations: { ru: "Да, скидка десять процентов", uz: "Ha, o‘n foiz chegirma bor" }, audio: { expectedPath: "assets/audio/dialogue/03A/03A-D01-T04.mp3" } },
{ id: "03A-D01-T05", speaker: "learner", arabic: "تَمَام، أَبْغَى هَذَا", translations: { ru: "Хорошо, я беру это", uz: "Yaxshi, men buni olaman" }, audio: { expectedPath: "assets/audio/dialogue/03A/03A-D01-T05.mp3" } }
] },
{ id: "03A-D02", context: "size", translations: { ru: "Размер", uz: "O‘lcham" }, turns: [
{ id: "03A-D02-T01", speaker: "learner", arabic: "عِنْدَك مَقَاس أَكْبَر؟", translations: { ru: "У вас есть размер побольше?", uz: "Kattaroq o‘lcham bormi?" }, audio: { expectedPath: "assets/audio/dialogue/03A/03A-D02-T01.mp3" } },
{ id: "03A-D02-T02", speaker: "interlocutor", arabic: "أَيْوَه، عِنْدِي", translations: { ru: "Да, есть", uz: "Ha, bor" }, audio: { expectedPath: "assets/audio/dialogue/03A/03A-D02-T02.mp3" } },
{ id: "03A-D02-T03", speaker: "learner", arabic: "مُمْكِن أَشُوفَه؟", translations: { ru: "Можно посмотреть?", uz: "Ko‘rsam bo‘ladimi?" }, audio: { expectedPath: "assets/audio/dialogue/03A/03A-D02-T03.mp3" } },
{ id: "03A-D02-T04", speaker: "interlocutor", arabic: "أَيْوَه، أَكِيد", translations: { ru: "Да, конечно", uz: "Ha, albatta" }, audio: { expectedPath: "assets/audio/dialogue/03A/03A-D02-T04.mp3" } },
{ id: "03A-D02-T05", speaker: "learner", arabic: "تَمَام، أَبْغَى هَذَا المَقَاس", translations: { ru: "Хорошо, мне нужен этот размер", uz: "Yaxshi, menga shu o‘lcham kerak" }, audio: { expectedPath: "assets/audio/dialogue/03A/03A-D02-T05.mp3" } }
] },
{ id: "03A-D03", context: "checkout", translations: { ru: "Оплата", uz: "To‘lov" }, turns: [
{ id: "03A-D03-T01", speaker: "interlocutor", arabic: "نَقْد وَلَّا بِطَاقَة؟", translations: { ru: "Наличными или картой?", uz: "Naqd pulmi yoki kartami?" }, audio: { expectedPath: "assets/audio/dialogue/03A/03A-D03-T01.mp3" } },
{ id: "03A-D03-T02", speaker: "learner", arabic: "بِالْبِطَاقَة، لَو سَمَحْت", translations: { ru: "Картой, пожалуйста", uz: "Karta bilan, iltimos" }, audio: { expectedPath: "assets/audio/dialogue/03A/03A-D03-T02.mp3" } },
{ id: "03A-D03-T03", speaker: "interlocutor", arabic: "تَبْغَى كِيس؟", translations: { ru: "Вам нужен пакет?", uz: "Paket kerakmi?" }, audio: { expectedPath: "assets/audio/dialogue/03A/03A-D03-T03.mp3" } },
{ id: "03A-D03-T04", speaker: "learner", arabic: "أَيْوَه، لَو سَمَحْت", translations: { ru: "Да, пожалуйста", uz: "Ha, iltimos" }, audio: { expectedPath: "assets/audio/dialogue/03A/03A-D03-T04.mp3" } },
{ id: "03A-D03-T05", speaker: "interlocutor", arabic: "تَمَام", translations: { ru: "Хорошо", uz: "Yaxshi" }, audio: { expectedPath: "assets/audio/dialogue/03A/03A-D03-T05.mp3" } },
{ id: "03A-D03-T06", speaker: "learner", arabic: "شُكْرًا", translations: { ru: "Спасибо", uz: "Rahmat" }, audio: { expectedPath: "assets/audio/dialogue/03A/03A-D03-T06.mp3" } }
] }
], practiceScenarios: [
{ id: "03A-P01", titles: { ru: "Купить товар", uz: "Mahsulot sotib olish" }, goal: { ru: "Узнать цену, спросить о скидке и выбрать товар", uz: "Narxni bilish, chegirma haqida so‘rash va mahsulotni tanlash" }, steps: [
{ id: "03A-P01-S01", intentId: "ASK_PRICE", responses: [{ id: "03A-P01-S01-R01", arabic: "بِكَم هَذَا؟", translations: { ru: "Сколько это стоит?", uz: "Bu qancha turadi?" } }] },
{ id: "03A-P01-S02", intentId: "ASK_DISCOUNT", responses: [{ id: "03A-P01-S02-R01", arabic: "فِيه خَصْم؟", translations: { ru: "Есть скидка?", uz: "Chegirma bormi?" } }, { id: "03A-P01-S02-R02", arabic: "فِيه خَصْم عَلَى هَذَا؟", translations: { ru: "На это есть скидка?", uz: "Bunga chegirma bormi?" } }] },
{ id: "03A-P01-S03", intentId: "ACCEPT_PRODUCT", responses: [{ id: "03A-P01-S03-R01", arabic: "أَبْغَى هَذَا", translations: { ru: "Я хочу это", uz: "Men buni xohlayman" } }, { id: "03A-P01-S03-R02", arabic: "أَبْغَى هَذَا، لَو سَمَحْت", translations: { ru: "Я хочу это, пожалуйста", uz: "Men buni xohlayman, iltimos" } }, { id: "03A-P01-S03-R03", arabic: "تَمَام، أَبْغَى هَذَا", translations: { ru: "Хорошо, я беру это", uz: "Yaxshi, men buni olaman" } }] }
] },
{ id: "03A-P02", titles: { ru: "Найти размер", uz: "O‘lcham topish" }, goal: { ru: "Попросить размер побольше, посмотреть его и выбрать размер", uz: "Kattaroq o‘lchamni so‘rash, uni ko‘rish va o‘lchamni tanlash" }, steps: [
{ id: "03A-P02-S01", intentId: "ASK_LARGER_SIZE", responses: [{ id: "03A-P02-S01-R01", arabic: "عِنْدَك مَقَاس أَكْبَر؟", translations: { ru: "У вас есть размер побольше?", uz: "Kattaroq o‘lcham bormi?" } }, { id: "03A-P02-S01-R02", arabic: "أَبْغَى مَقَاس أَكْبَر مِن هَذَا", translations: { ru: "Мне нужен размер побольше этого", uz: "Menga bundan kattaroq o‘lcham kerak" } }] },
{ id: "03A-P02-S02", intentId: "ASK_TO_SEE", responses: [{ id: "03A-P02-S02-R01", arabic: "مُمْكِن أَشُوفَه؟", translations: { ru: "Можно посмотреть?", uz: "Ko‘rsam bo‘ladimi?" } }] },
{ id: "03A-P02-S03", intentId: "ACCEPT_SIZE", responses: [{ id: "03A-P02-S03-R01", arabic: "تَمَام، أَبْغَى هَذَا المَقَاس", translations: { ru: "Хорошо, мне нужен этот размер", uz: "Yaxshi, menga shu o‘lcham kerak" } }] }
] },
{ id: "03A-P03", titles: { ru: "Оплатить", uz: "To‘lash" }, goal: { ru: "Сообщить об оплате картой и самостоятельно попросить пакет", uz: "Karta bilan to‘lashni aytish va mustaqil paket so‘rash" }, steps: [
{ id: "03A-P03-S01", intentId: "PAY_BY_CARD", responses: [{ id: "03A-P03-S01-R01", arabic: "بِالْبِطَاقَة، لَو سَمَحْت", translations: { ru: "Картой, пожалуйста", uz: "Karta bilan, iltimos" } }, { id: "03A-P03-S01-R02", arabic: "بَدْفَع بِالْبِطَاقَة", translations: { ru: "Я оплачу картой", uz: "Karta bilan to‘layman" } }, { id: "03A-P03-S01-R03", arabic: "مُمْكِن أَدْفَع بِالْبِطَاقَة؟", translations: { ru: "Можно оплатить картой?", uz: "Karta bilan to‘lasam bo‘ladimi?" } }] },
{ id: "03A-P03-S02", intentId: "ASK_FOR_BAG", responses: [{ id: "03A-P03-S02-R01", arabic: "مُمْكِن كِيس، لَو سَمَحْت؟", translations: { ru: "Можно пакет, пожалуйста?", uz: "Paket mumkinmi, iltimos?" } }, { id: "03A-P03-S02-R02", arabic: "أَبْغَى كِيس", translations: { ru: "Мне пакет", uz: "Menga paket kerak" } }] }
] }
], understand: [
{ id: "03A-U01", questionArabic: "إِيش تَبْغَى؟", questionTranslations: { ru: "Что вы хотите?", uz: "Nima xohlaysiz?" }, answerArabic: "أَبْغَى هَذَا، لَو سَمَحْت", answerTranslations: { ru: "Я хочу это, пожалуйста", uz: "Men buni xohlayman, iltimos" }, answerChunks: ["أَبْغَى", "هَذَا،", "لَو سَمَحْت"], build: { answerChunkIds: ["03A-U01-B1", "03A-U01-B2", "03A-U01-B3"], chunks: [{ id: "03A-U01-B1", arabic: "أَبْغَى" }, { id: "03A-U01-B2", arabic: "هَذَا،" }, { id: "03A-U01-B3", arabic: "لَو سَمَحْت" }, { id: "03A-U01-B4", arabic: "عِنْدِي" }, { id: "03A-U01-B5", arabic: "هُنَاك" }] }, choices: [{ id: "03A-U01-C1", arabic: "أَبْغَى هَذَا، لَو سَمَحْت", correct: true }, { id: "03A-U01-C2", arabic: "بِالْبِطَاقَة، لَو سَمَحْت", correct: false }, { id: "03A-U01-C3", arabic: "أَيْوَه، عِنْدِي", correct: false }] },
{ id: "03A-U02", questionArabic: "بِكَم هَذَا؟", questionTranslations: { ru: "Сколько это стоит?", uz: "Bu qancha turadi?" }, answerArabic: "بِعِشْرِين رِيَال", answerTranslations: { ru: "Двадцать риялов", uz: "Yigirma riyol" }, answerChunks: ["بِعِشْرِين", "رِيَال"], build: { answerChunkIds: ["03A-U02-B1", "03A-U02-B2"], chunks: [{ id: "03A-U02-B1", arabic: "بِعِشْرِين" }, { id: "03A-U02-B2", arabic: "رِيَال" }, { id: "03A-U02-B3", arabic: "حَبَّتَيْن" }, { id: "03A-U02-B4", arabic: "كِيلُو" }] }, choices: [{ id: "03A-U02-C1", arabic: "بِعِشْرِين رِيَال", correct: true }, { id: "03A-U02-C2", arabic: "أَبْغَى حَبَّتَيْن", correct: false }, { id: "03A-U02-C3", arabic: "هُنَاك", correct: false }] },
{ id: "03A-U03", questionArabic: "فِيه خَصْم؟", questionTranslations: { ru: "Есть скидка?", uz: "Chegirma bormi?" }, answerArabic: "أَيْوَه، فِيه خَصْم", answerTranslations: { ru: "Да, есть скидка", uz: "Ha, chegirma bor" }, answerChunks: ["أَيْوَه،", "فِيه", "خَصْم"], build: { answerChunkIds: ["03A-U03-B1", "03A-U03-B2", "03A-U03-B3"], chunks: [{ id: "03A-U03-B1", arabic: "أَيْوَه،" }, { id: "03A-U03-B2", arabic: "فِيه" }, { id: "03A-U03-B3", arabic: "خَصْم" }, { id: "03A-U03-B4", arabic: "مَا" }, { id: "03A-U03-B5", arabic: "عِنْدِي" }] }, choices: [{ id: "03A-U03-C1", arabic: "أَيْوَه، فِيه خَصْم", correct: true }, { id: "03A-U03-C2", arabic: "بِعِشْرِين رِيَال", correct: false }, { id: "03A-U03-C3", arabic: "لَا، مَا عِنْدِي", correct: false }] },
{ id: "03A-U04", questionArabic: "عِنْدَك مَقَاس أَكْبَر؟", questionTranslations: { ru: "У вас есть размер побольше?", uz: "Kattaroq o‘lcham bormi?" }, answerArabic: "أَيْوَه، عِنْدِي", answerTranslations: { ru: "Да, есть", uz: "Ha, bor" }, answerChunks: ["أَيْوَه،", "عِنْدِي"], build: { answerChunkIds: ["03A-U04-B1", "03A-U04-B2"], chunks: [{ id: "03A-U04-B1", arabic: "أَيْوَه،" }, { id: "03A-U04-B2", arabic: "عِنْدِي" }, { id: "03A-U04-B3", arabic: "مَا" }, { id: "03A-U04-B4", arabic: "هُنَاك" }] }, choices: [{ id: "03A-U04-C1", arabic: "أَيْوَه، عِنْدِي", correct: true }, { id: "03A-U04-C2", arabic: "أَبْغَى كِيلُو وَاحِد", correct: false }, { id: "03A-U04-C3", arabic: "هُنَاك", correct: false }] },
{ id: "03A-U05", questionArabic: "عِنْدَك مَقَاس أَصْغَر؟", questionTranslations: { ru: "У вас есть размер поменьше?", uz: "Kichikroq o‘lcham bormi?" }, answerArabic: "لَا، مَا عِنْدِي", answerTranslations: { ru: "Нет, у меня нет", uz: "Yo‘q, menda yo‘q" }, answerChunks: ["لَا،", "مَا", "عِنْدِي"], build: { answerChunkIds: ["03A-U05-B1", "03A-U05-B2", "03A-U05-B3"], chunks: [{ id: "03A-U05-B1", arabic: "لَا،" }, { id: "03A-U05-B2", arabic: "مَا" }, { id: "03A-U05-B3", arabic: "عِنْدِي" }, { id: "03A-U05-B4", arabic: "أَيْوَه،" }, { id: "03A-U05-B5", arabic: "أَكِيد" }] }, choices: [{ id: "03A-U05-C1", arabic: "لَا، مَا عِنْدِي", correct: true }, { id: "03A-U05-C2", arabic: "أَيْوَه، أَكِيد", correct: false }, { id: "03A-U05-C3", arabic: "بِالْبِطَاقَة، لَو سَمَحْت", correct: false }] },
{ id: "03A-U06", questionArabic: "كَم حَبَّة تَبْغَى؟", questionTranslations: { ru: "Сколько штук вы хотите?", uz: "Nechta xohlaysiz?" }, answerArabic: "أَبْغَى حَبَّتَيْن", answerTranslations: { ru: "Мне две штуки", uz: "Menga ikkita kerak" }, answerChunks: ["أَبْغَى", "حَبَّتَيْن"], build: { answerChunkIds: ["03A-U06-B1", "03A-U06-B2"], chunks: [{ id: "03A-U06-B1", arabic: "أَبْغَى" }, { id: "03A-U06-B2", arabic: "حَبَّتَيْن" }, { id: "03A-U06-B3", arabic: "كِيلُو" }, { id: "03A-U06-B4", arabic: "رِيَال" }] }, choices: [{ id: "03A-U06-C1", arabic: "أَبْغَى حَبَّتَيْن", correct: true }, { id: "03A-U06-C2", arabic: "أَبْغَى كِيلُو وَاحِد", correct: false }, { id: "03A-U06-C3", arabic: "بِعِشْرِين رِيَال", correct: false }] },
{ id: "03A-U07", questionArabic: "كَم كِيلُو تَبْغَى؟", questionTranslations: { ru: "Сколько килограммов вы хотите?", uz: "Necha kilogramm xohlaysiz?" }, answerArabic: "أَبْغَى كِيلُو وَاحِد", answerTranslations: { ru: "Мне один килограмм", uz: "Menga bir kilogramm kerak" }, answerChunks: ["أَبْغَى", "كِيلُو", "وَاحِد"], build: { answerChunkIds: ["03A-U07-B1", "03A-U07-B2", "03A-U07-B3"], chunks: [{ id: "03A-U07-B1", arabic: "أَبْغَى" }, { id: "03A-U07-B2", arabic: "كِيلُو" }, { id: "03A-U07-B3", arabic: "وَاحِد" }, { id: "03A-U07-B4", arabic: "حَبَّتَيْن" }, { id: "03A-U07-B5", arabic: "رِيَال" }] }, choices: [{ id: "03A-U07-C1", arabic: "أَبْغَى كِيلُو وَاحِد", correct: true }, { id: "03A-U07-C2", arabic: "أَبْغَى حَبَّتَيْن", correct: false }, { id: "03A-U07-C3", arabic: "أَيْوَه، عِنْدِي", correct: false }] },
{ id: "03A-U08", questionArabic: "نَقْد وَلَّا بِطَاقَة؟", questionTranslations: { ru: "Наличными или картой?", uz: "Naqd pulmi yoki kartami?" }, answerArabic: "بِالْبِطَاقَة، لَو سَمَحْت", answerTranslations: { ru: "Картой, пожалуйста", uz: "Karta bilan, iltimos" }, answerChunks: ["بِالْبِطَاقَة،", "لَو سَمَحْت"], build: { answerChunkIds: ["03A-U08-B1", "03A-U08-B2"], chunks: [{ id: "03A-U08-B1", arabic: "بِالْبِطَاقَة،" }, { id: "03A-U08-B2", arabic: "لَو سَمَحْت" }, { id: "03A-U08-B3", arabic: "نَقْد" }, { id: "03A-U08-B4", arabic: "هُنَاك" }] }, choices: [{ id: "03A-U08-C1", arabic: "بِالْبِطَاقَة، لَو سَمَحْت", correct: true }, { id: "03A-U08-C2", arabic: "بِعِشْرِين رِيَال", correct: false }, { id: "03A-U08-C3", arabic: "هُنَاك", correct: false }] },
{ id: "03A-U09", questionArabic: "مُمْكِن كِيس؟", questionTranslations: { ru: "Можно пакет?", uz: "Paket mumkinmi?" }, answerArabic: "أَيْوَه، أَكِيد", answerTranslations: { ru: "Да, конечно", uz: "Ha, albatta" }, answerChunks: ["أَيْوَه،", "أَكِيد"], build: { answerChunkIds: ["03A-U09-B1", "03A-U09-B2"], chunks: [{ id: "03A-U09-B1", arabic: "أَيْوَه،" }, { id: "03A-U09-B2", arabic: "أَكِيد" }, { id: "03A-U09-B3", arabic: "مَا" }, { id: "03A-U09-B4", arabic: "عِنْدِي" }] }, choices: [{ id: "03A-U09-C1", arabic: "أَيْوَه، أَكِيد", correct: true }, { id: "03A-U09-C2", arabic: "لَا، مَا عِنْدِي", correct: false }, { id: "03A-U09-C3", arabic: "أَبْغَى حَبَّتَيْن", correct: false }] },
{ id: "03A-U10", questionArabic: "وَيْن الكَاشِير؟", questionTranslations: { ru: "Где касса?", uz: "Kassa qayerda?" }, answerArabic: "هُنَاك", answerTranslations: { ru: "Там", uz: "U yerda" }, answerChunks: ["هُنَاك"], build: { answerChunkIds: ["03A-U10-B1"], chunks: [{ id: "03A-U10-B1", arabic: "هُنَاك" }, { id: "03A-U10-B2", arabic: "عِنْدِي" }, { id: "03A-U10-B3", arabic: "أَكِيد" }, { id: "03A-U10-B4", arabic: "رِيَال" }] }, choices: [{ id: "03A-U10-C1", arabic: "هُنَاك", correct: true }, { id: "03A-U10-C2", arabic: "بِالْبِطَاقَة، لَو سَمَحْت", correct: false }, { id: "03A-U10-C3", arabic: "أَيْوَه، فِيه خَصْم", correct: false }] }
] }
].map((lesson) => ({ ...lesson, words: lesson.words.map(([id, arabic, ru, uz, letters, hasAudio = true, imageSrc]) => { const path = `assets/audio/words/word-${String(id).padStart(3, "0")}.mp3`; return { id, arabic, translations: { ru, uz }, letters, audio: hasAudio ? { src: path, expectedPath: path } : {}, image: imageSrc ? { src: imageSrc } : {} }; }), understand: Array.isArray(lesson.understand) ? lesson.understand.map((item) => ({ ...item, questionAudio: { src: understandQuestionAudioPaths[item.id], expectedPath: understandQuestionAudioPaths[item.id] } })) : lesson.understand }));
const allWords = lessons.flatMap((lesson) => lesson.words);
