const translations = {
  ru: { homeEyebrow:"Учимся понемногу каждый день", greeting:"Ассаляму алейкум", intro:"Продолжайте знакомство с арабскими словами в своём темпе.", overall:"Общий прогресс", progressSummary:"Ваш прогресс", answer:"Ваш ответ", letters:"Буквы для выбора", words:"{current} / {total} слов", streak:"Серия: {count} {unit}", day:"день", days:"дней", continue:"Продолжить: {lesson}", lessons:"Уроки", lessonCount:"{count} урока", lesson:"Урок {count}", lessonProgress:"Прогресс урока", wordPosition:"Слово {current} из {total}", back:"← Все уроки", build:"🧩 Собрать слово", known:"✓ Я знаю", repeat:"Повторить", builderEyebrow:"Проверь себя", builderTitle:"Собери слово", builderInstruction:"Выберите буквы в правильном порядке.", reset:"Начать заново", check:"Проверить", next:"Следующее слово", correct:"Верно! +10 XP за новое освоенное слово.", wrong:"Почти. Правильно: {word}", audioMissing:"Произношение скоро", audioMissingStatus:"Проверенная запись для этого слова ещё не добавлена.", audioPlay:"Прослушать произношение", audioLoading:"Загрузка…", audioReplay:"Повторить произношение", audioPlaying:"Воспроизводится запись.", audioRetry:"Попробовать ещё раз", audioError:"Не удалось загрузить запись. Попробуйте ещё раз позже.", russian:"Русский", uzbek:"O‘zbekcha", language:"Язык" },
  uz: { homeEyebrow:"Har kuni oz-ozdan o‘rganing", greeting:"Assalomu alaykum", intro:"Arabcha so‘zlarni o‘z sur’atingizda o‘rganishda davom eting.", overall:"Umumiy rivojlanish", progressSummary:"Sizning rivojlanishingiz", answer:"Javobingiz", letters:"Tanlash uchun harflar", words:"{current} / {total} so‘z", streak:"Ketma-ketlik: {count} kun", day:"kun", days:"kun", continue:"Davom etish: {lesson}", lessons:"Darslar", lessonCount:"{count} ta dars", lesson:"{count}-dars", lessonProgress:"Dars rivoji", wordPosition:"{current}-so‘z / {total}", back:"← Barcha darslar", build:"🧩 So‘zni tuzish", known:"✓ Bilaman", repeat:"Takrorlash", builderEyebrow:"O‘zingizni sinang", builderTitle:"So‘zni tuzing", builderInstruction:"Harflarni to‘g‘ri tartibda tanlang.", reset:"Qaytadan boshlash", check:"Tekshirish", next:"Keyingi so‘z", correct:"To‘g‘ri! Yangi o‘zlashtirilgan so‘z uchun +10 XP.", wrong:"Yana urinib ko‘ring. To‘g‘ri javob: {word}", audioMissing:"Talaffuz tez orada", audioMissingStatus:"Bu so‘z uchun tasdiqlangan yozuv hali qo‘shilmagan.", audioPlay:"Talaffuzni tinglash", audioLoading:"Yuklanmoqda…", audioReplay:"Talaffuzni qayta tinglash", audioPlaying:"Yozuv ijro etilmoqda.", audioRetry:"Yana urinib ko‘rish", audioError:"Yozuvni yuklab bo‘lmadi. Keyinroq qayta urinib ko‘ring.", russian:"Русский", uzbek:"O‘zbekcha", language:"Til" }
};
Object.assign(translations.ru, { lessonCompleteEyebrow:"Урок завершён", lessonCompleteTitle:"Отличная работа!", lessonCompleteDescription:"Вы освоили все слова урока.", nextLesson:"Следующий урок", allLessonsComplete:"Все уроки пройдены", allLessonsCompleteDescription:"Повторяйте слова, чтобы закрепить знания.", backToLessons:"← Все уроки", reviewLesson:"Пройти ещё раз" });
Object.assign(translations.uz, { lessonCompleteEyebrow:"Dars tugadi", lessonCompleteTitle:"Ajoyib ishladingiz!", lessonCompleteDescription:"Darsdagi barcha so‘zlarni o‘zlashtirdingiz.", nextLesson:"Keyingi dars", allLessonsComplete:"Barcha darslar tugadi", allLessonsCompleteDescription:"Bilimni mustahkamlash uchun so‘zlarni takrorlang.", backToLessons:"← Barcha darslar", reviewLesson:"Qayta o‘tish" });
let activeLocale = "ru";
function setLocale(locale) { activeLocale = translations[locale] ? locale : "ru"; document.documentElement.lang = activeLocale; }
function t(key, params = {}) { const value = translations[activeLocale][key] || translations.ru[key] || key; return value.replace(/\{(\w+)\}/g, (_, keyName) => params[keyName] ?? `{${keyName}}`); }

Object.assign(translations.ru,{topicStages:'Этапы темы',stageWords:'Слова',stageSpeak:'Говори',stageExpand:'Расширяй',stageUnderstand:'Пойми и ответь',stageDialogue:'Диалог',stagePractice:'Практика',stageComingSoon:'Скоро',speakStageKicker:'02 · Говори',speakKeyLabel:'Речевой ключ',speakKeyDetailsTitle:'Речевой ключ',speakKeyClose:'Закрыть',speakPractice:'Тренироваться',speakAssemblyInstruction:'Соберите фразу',speakAssemblyAnswer:'Ваш ответ',speakAssemblyOptions:'Части фразы',speakAssemblyReset:'Сбросить',speakAssemblyCheck:'Проверить',speakAssemblyCorrect:'Правильно. Фраза собрана.',speakAssemblyWrong:'Порядок пока неверный. Попробуйте ещё раз.',speakPrevious:'Назад',speakNext:'Далее',speakPosition:'{current} / {total}'});
Object.assign(translations.uz,{topicStages:'Mavzu bosqichlari',stageWords:'So‘zlar',stageSpeak:'Gapir',stageExpand:'Kengaytir',stageUnderstand:'Tushun va javob ber',stageDialogue:'Dialog',stagePractice:'Mashq',stageComingSoon:'Tez orada',speakStageKicker:'02 · Gapir',speakKeyLabel:'Nutq kaliti',speakKeyDetailsTitle:'Nutq kaliti',speakKeyClose:'Yopish',speakPractice:'Mashq qilish',speakAssemblyInstruction:'Gapni tuzing',speakAssemblyAnswer:'Javobingiz',speakAssemblyOptions:'Gap qismlari',speakAssemblyReset:'Qayta boshlash',speakAssemblyCheck:'Tekshirish',speakAssemblyCorrect:'To‘g‘ri. Gap tuzildi.',speakAssemblyWrong:'Tartib hali to‘g‘ri emas. Yana urinib ko‘ring.',speakPrevious:'Orqaga',speakNext:'Keyingi',speakPosition:'{current} / {total}'});
Object.assign(translations.ru,{expandStageKicker:'03 · Расширяй',expandBaseLabel:'Знакомая конструкция',expandAddedLabel:'Новый элемент',expandPhraseLabel:'Расширенная фраза',expandPrevious:'Назад',expandNext:'Далее',expandPosition:'{current} / {total}'});
Object.assign(translations.uz,{expandStageKicker:'03 · Kengaytir',expandBaseLabel:'Tanish konstruksiya',expandAddedLabel:'Yangi element',expandPhraseLabel:'Kengaytirilgan gap',expandPrevious:'Orqaga',expandNext:'Keyingi',expandPosition:'{current} / {total}'});
Object.assign(translations.ru,{expandPractice:'Тренироваться',expandAssemblyInstruction:'Соберите расширенную фразу',expandAssemblyAnswer:'Ваш ответ',expandAssemblyOptions:'Части фразы',expandAssemblyReset:'Сбросить',expandAssemblyCheck:'Проверить',expandAssemblyCorrect:'Правильно. Расширенная фраза собрана.',expandAssemblyWrong:'Порядок пока неверный. Попробуйте ещё раз.'});
Object.assign(translations.uz,{expandPractice:'Mashq qilish',expandAssemblyInstruction:'Kengaytirilgan gapni tuzing',expandAssemblyAnswer:'Javobingiz',expandAssemblyOptions:'Gap qismlari',expandAssemblyReset:'Qayta boshlash',expandAssemblyCheck:'Tekshirish',expandAssemblyCorrect:'To‘g‘ri. Kengaytirilgan gap tuzildi.',expandAssemblyWrong:'Tartib hali to‘g‘ri emas. Yana urinib ko‘ring.'});
Object.assign(translations.ru,{understandStageKicker:'04 · Пойми и ответь',understandQuestionLabel:'Вопрос',understandAnswerLabel:'Ответ',understandPrevious:'Назад',understandNext:'Далее',understandPosition:'{current} / {total}'});
Object.assign(translations.uz,{understandStageKicker:'04 · Tushun va javob ber',understandQuestionLabel:'Savol',understandAnswerLabel:'Javob',understandPrevious:'Orqaga',understandNext:'Keyingi',understandPosition:'{current} / {total}'});
Object.assign(translations.ru,{understandAudioPlay:'Прослушать вопрос',understandAudioReplay:'Прослушать ещё раз',understandAudioLoading:'Загрузка...',understandAudioPlaying:'Воспроизводится...',understandAudioRetry:'Повторить попытку',understandAudioError:'Не удалось воспроизвести аудио.',understandAudioMissing:'Аудио скоро',understandAudioMissingStatus:'Запись вопроса пока недоступна.'});
Object.assign(translations.uz,{understandAudioPlay:'Savolni tinglash',understandAudioReplay:'Yana tinglash',understandAudioLoading:'Yuklanmoqda...',understandAudioPlaying:'Ijro etilmoqda...',understandAudioRetry:'Qayta urinish',understandAudioError:'Audioni ijro etib bo‘lmadi.',understandAudioMissing:'Audio tez orada',understandAudioMissingStatus:'Savol yozuvi hozircha mavjud emas.'});
Object.assign(translations.ru,{understandModeRead:'С переводом',understandModeArabic:'Только арабский',understandModeLabel:'Режим подсказки'});Object.assign(translations.uz,{understandModeRead:'Tarjima bilan',understandModeArabic:'Faqat arabcha',understandModeLabel:'Yordam rejimi'});
Object.assign(translations.ru,{understandModeChoice:'Только аудио',understandChoiceInstruction:'Прослушай и выбери ответ',understandChoiceHelp:'Подсказка',understandChoiceWrong:'Попробуйте ещё раз',understandChoiceCorrect:'Верно',understandChoiceSelectedWrong:'Неверный вариант',understandChoiceSelectedCorrect:'Верный вариант'});Object.assign(translations.uz,{understandModeChoice:'Faqat audio',understandChoiceInstruction:'Tinglang va javobni tanlang',understandChoiceHelp:'Yordam',understandChoiceWrong:'Yana urinib ko‘ring',understandChoiceCorrect:'To‘g‘ri',understandChoiceSelectedWrong:'Noto‘g‘ri variant',understandChoiceSelectedCorrect:'To‘g‘ri variant'});
Object.assign(translations.ru,{understandModeBuild:'Собери ответ',understandBuildInstruction:'Прослушай и собери ответ',understandBuildCheck:'Проверить',understandBuildWrong:'Попробуй ещё раз',understandBuildCorrect:'Верно',understandBuildUnavailable:'Сборка ответа пока недоступна.'});Object.assign(translations.uz,{understandModeBuild:'Javobni tuzing',understandBuildInstruction:'Tinglang va javobni tuzing',understandBuildCheck:'Tekshirish',understandBuildWrong:'Yana urinib ko‘ring',understandBuildCorrect:'To‘g‘ri',understandBuildUnavailable:'Javobni tuzish hozircha mavjud emas.'});
Object.assign(translations.ru,{audioSpeed:'Скорость аудио'});Object.assign(translations.uz,{audioSpeed:'Audio tezligi'});
Object.assign(translations.ru,{dialogueStageKicker:'05 · Диалог',dialoguePosition:'{current} / {total}',dialogueLearner:'Вы',dialogueInterlocutor:'Собеседник',dialoguePrevious:'Назад',dialogueNext:'Далее'});Object.assign(translations.uz,{dialogueStageKicker:'05 · Dialog',dialoguePosition:'{current} / {total}',dialogueLearner:'Siz',dialogueInterlocutor:'Suhbatdosh',dialoguePrevious:'Orqaga',dialogueNext:'Keyingi'});
Object.assign(translations.ru,{dialogueTurnPosition:'Реплика {current} из {total}',dialoguePreviousScene:'Предыдущая сцена',dialogueContinue:'Продолжить',dialogueNextScene:'Следующая сцена',dialogueReviewed:'Диалог просмотрен'});Object.assign(translations.uz,{dialogueTurnPosition:'Replika {current} / {total}',dialoguePreviousScene:'Oldingi sahna',dialogueContinue:'Davom etish',dialogueNextScene:'Keyingi sahna',dialogueReviewed:'Dialog ko‘rib chiqildi'});
Object.assign(translations.ru,{dialogueAudioPlay:'Прослушать реплику',dialogueAudioLoading:'Загрузка…',dialogueAudioReplay:'Прослушать ещё раз',dialogueAudioPlaying:'Реплика воспроизводится.',dialogueAudioRetry:'Повторить попытку',dialogueAudioError:'Не удалось воспроизвести реплику.',dialogueAudioMissing:'Аудио скоро',dialogueAudioMissingStatus:'Аудио для этой реплики пока недоступно.'});Object.assign(translations.uz,{dialogueAudioPlay:'Replikani tinglash',dialogueAudioLoading:'Yuklanmoqda…',dialogueAudioReplay:'Yana tinglash',dialogueAudioPlaying:'Replika ijro etilmoqda.',dialogueAudioRetry:'Qayta urinish',dialogueAudioError:'Replikani ijro etib bo‘lmadi.',dialogueAudioMissing:'Audio tez orada',dialogueAudioMissingStatus:'Bu replika uchun audio hozircha mavjud emas.'});
Object.assign(translations.ru,{dialogueModeLabel:'Режим поддержки',dialogueModeRead:'С переводом',dialogueModeArabic:'Только арабский'});Object.assign(translations.uz,{dialogueModeLabel:'Yordam rejimi',dialogueModeRead:'Tarjima bilan',dialogueModeArabic:'Faqat arabcha'});
Object.assign(translations.ru,{dialogueRevealInstruction:'Сформулируйте ответ',dialogueReveal:'Показать реплику'});Object.assign(translations.uz,{dialogueRevealInstruction:'Javobni ayting',dialogueReveal:'Replikani ko‘rsatish'});
Object.assign(translations.ru,{practiceStageKicker:'06 · Практика',practiceScenarioPosition:'Ситуация {current} из {total}',practiceStepPosition:'Шаг {current} из {total}',practiceInstruction:'Сформулируйте ответ',practiceContinue:'Продолжить',practiceCompleted:'Практика пройдена',practiceReview:'Повторить практику'});Object.assign(translations.uz,{practiceStageKicker:'06 · Mashq',practiceScenarioPosition:'Vaziyat {current} / {total}',practiceStepPosition:'Qadam {current} / {total}',practiceInstruction:'Javobni ayting',practiceContinue:'Davom etish',practiceCompleted:'Mashq yakunlandi',practiceReview:'Mashqni takrorlash'});
Object.assign(translations.ru,{practiceReveal:'Показать варианты',practiceResponseLabel:'Возможный вариант'});Object.assign(translations.uz,{practiceReveal:'Variantlarni ko‘rsatish',practiceResponseLabel:'Mumkin variant'});
Object.assign(translations.ru,{continueLearning:'Продолжить обучение',startLearning:'Начать обучение',stageCompleted:'Завершено',lessonCompleted:'Урок завершён'});Object.assign(translations.uz,{continueLearning:'O‘qishni davom ettirish',startLearning:'O‘qishni boshlash',stageCompleted:'Yakunlandi',lessonCompleted:'Dars yakunlandi'});
Object.assign(translations.ru,{foundationKicker:"Для начинающих",foundationTitle:"Арабский с нуля",foundationDescription:"Научитесь читать арабские буквы шаг за шагом.",foundationStart:"Начать",alphabetBack:"← На главную",alphabetDescription:"Сначала буквы, потом чтение. Понемногу и по порядку."});
Object.assign(translations.uz,{foundationKicker:"Boshlovchilar uchun",foundationTitle:"Arab tili noldan",foundationDescription:"Arab harflarini bosqichma-bosqich o\u2018qishni o\u2018rganing.",foundationStart:"Boshlash",alphabetBack:"← Bosh sahifa",alphabetDescription:"Avval harflar, keyin o\u2018qish. Oz-ozdan va tartib bilan."});
